Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Employee.Models;
using Employee.Models.config;
using MySql.Data.MySqlClient;
using System.Data;

namespace Employee.Controllers
{
    public class EmployeeController : Controller
    {
        Connection dbCon = new Connection();
        ErrorMessage message=new ErrorMessage();
        List<ClsEmployess> List_emp = new List<ClsEmployess>();
        ClsEmployess obj_emp;
        public IActionResult Employee()
        {
            //getEmployee();
            return View();
        }
        private byte[] img {get;set;}
        private string imageType{get;set;}
        private string query {get;set;}
        [HttpPost]
        public IActionResult postEmployee(ClsEmployess obj_em)
        {
            
            try
            {
                if(message.errCode==0)
                {
                    //now we need convert string to binary code
                    img = Convert.FromBase64String(obj_em.image);
                    //is true
                    query="INSERT INTO `tblemployess`(`names`, `gender`, `dob`, `position`, `phone`, `addresss`, `hiredate`, `salary`, `imgType`, `image`) VALUES (N'"+obj_em.name+"',N'" + obj_em.gender + "','" + obj_em.dob + "',N'" + obj_em.position + "',N'" + obj_em.phone + "',N'" + obj_em.address + "','" + obj_em.hireDate + "','" + obj_em.sallary + "','"+obj_em.imgType+"',@img)";

                    MySqlCommand command = new MySqlCommand(query,dbCon.connection);
                    command.Parameters.AddWithValue("@img",img);
                    command.ExecuteNonQuery();
                    message.errCode=1;
                    message.errMsg="Data wase Saved";//now sad like that how now please tell me ,thanks
                   
                }
                else
                {
                    //is false
                    message.errCode = 101;
                    message.errMsg = "Data wase not Saved";
                }
            }
            catch(Exception ex)
            {
                message.errCode=ex.HResult;
                message.errMsg=ex.Message;
            }
            return Ok(message);
        }
        [HttpPost]
        public IActionResult UpdateEmployee(ClsEmployess obj_ems)
        {

            MySqlTransaction trans = dbCon.connection.BeginTransaction();
            try
            {
                if (message.errCode == 0)
                {
                    //now we need convert string to binary code
                    if(obj_ems.imgType!=null && obj_ems.image!=null)
                    {
                        img = Convert.FromBase64String(obj_ems.image);
                        imageType=obj_ems.imgType;
                    }
                    //is true
                    query = "UPDATE `tblemployess` SET `names`= '"+obj_ems.name+"',`gender`= '" + obj_ems.gender + "',`dob`= '" + obj_ems.dob + "',`position`= '" + obj_ems.position + "',`phone`= '" + obj_ems.phone + "',`addresss`= '" + obj_ems.address + "',`hiredate`= '" + obj_ems.hireDate + "',`salary`= '" + obj_ems.sallary + "',`imgType`= '" + imageType + "',`image`= @img WHERE `id`= "+obj_ems.empid;
                    MySqlCommand command = new MySqlCommand(query, dbCon.connection);
                    command.Parameters.AddWithValue("@img",img);
                    command.Transaction=trans;
                    command.ExecuteNonQuery();
                    message.errCode = 1;
                    message.errMsg = "Data wase updated";//now sad like that how now please tell me ,thanks
                    trans.Commit();
                }
                else
                {
                    //is false
                    message.errCode = 101;
                    message.errMsg = "Data wase not updated";
                }
            }
            catch (Exception ex)
            {
                message.errCode = ex.HResult;
                message.errMsg = ex.Message;
                trans.Rollback();
            }
            finally
            {
                trans.Dispose();
            }
            return Ok(message);
        }
        public IActionResult getEmployee()
        {
            try{
                if(message.errCode==0)
                {
                    String query_select="SELECT * FROM `tblemployess` ORDER BY id DESC";
                    MySqlDataAdapter dataAdapter = new MySqlDataAdapter(query_select,dbCon.connection);
                    DataTable dataTable = new DataTable();
                    dataAdapter.Fill(dataTable);
                    if(dataTable.Rows.Count>0)
                    {
                        foreach(DataRow dr in dataTable.Rows)
                        {
                            obj_emp=new ClsEmployess();
                            obj_emp.empid=int.Parse(dr[0].ToString());
                            obj_emp.name=dr[1].ToString();
                            obj_emp.gender=dr[2].ToString();
                            obj_emp.dob=dr[3].ToString();
                            obj_emp.position=dr[4].ToString();
                            obj_emp.phone=dr[5].ToString();
                            obj_emp.address=dr[6].ToString();
                            obj_emp.hireDate=dr[7].ToString();
                            obj_emp.sallary=decimal.Parse(dr[8].ToString());
                            obj_emp.imgType=dr[9].ToString();
                            //image we need to convert to binary
                            byte[] img=(byte[])dr[10];
                            //we convert to string
                            obj_emp.image=obj_emp.imgType+","+Convert.ToBase64String(img);
                            List_emp.Add(obj_emp);
                        }
                    }
                }
            }
            catch(Exception ex)
            {
                ViewBag.errCode=ex.HResult;
                ViewBag.errMsg=ex.Message;
            }
            return Ok(List_emp); 
        }

        public IActionResult deleteEmpoloyee(int empid)
        {
            try
            {
                if(message.errCode==0)
                {
                    query="DELETE FROM tblemployess WHERE id ="+empid;
                    MySqlCommand command = new MySqlCommand(query,dbCon.connection);
                    command.ExecuteNonQuery();
                    message.errMsg="Data was deleted successfully.";
                    message.errCode=1;
                }
                else 
                {
                    //false
                    message.errCode=323;
                    message.errMsg="Try connected again please";
                }
            }
            catch(Exception ex)
            {
                message.errCode=ex.HResult;
                message.errMsg=ex.Message;
            }
            return Ok(message);
        }
    }
}

Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Employee.Models.Product;
using Employee.Models;
using Employee.Models.config;
using MySql.Data.MySqlClient;
using System.Data;
using Microsoft.AspNetCore.Http;

namespace Employee.Controllers
{
    public class ProductController : Controller
    {  
        private  MySqlCommand command;
        private MySqlDataAdapter dataAdapter;
        private DataTable dataTable;
        private List<Categroy> ls_cate = new List<Categroy>();
        private List<ManageProduct> ls_pop = new List<ManageProduct>();
        private List<ManageProduct> ls_manage = new List<ManageProduct>();
        private ListProduct pro_obj_list = new ListProduct();
        private Connection db_con = new Connection();
        private string query;
        private byte[] img;
        private int cateid;
        public IActionResult HomeProduct(int get_cateid) 
        {
            if(!string.IsNullOrEmpty(HttpContext.Session.GetString("username"))) 
            {
                getDataFromdata();
                //ClothingMan(get_cateid);
                return View();
            }
            else return RedirectToAction("Index","Home");
            
        }

        public IActionResult getDataFromdata()
        {
            try
            {
                //get all category
                query="SELECT * FROM tblcategory";
                dataAdapter = new MySqlDataAdapter(query,db_con.connection);
                dataTable = new DataTable();
                dataAdapter.Fill(dataTable);
                if(dataTable.Rows.Count>0)
                {
                    foreach (DataRow dr in dataTable.Rows)
                    {
                        Categroy categroy = new Categroy();
                        categroy.cateId = int.Parse(dr[0].ToString());
                        categroy.catename = dr[1].ToString();
                        categroy.imgType = dr[2].ToString();
                        img = (byte[])dr[3];
                        categroy.image = Convert.ToBase64String(img);
                        ls_cate.Add(categroy);
                    }
                }
                ///=======================get Category End===========================///
                /// ///=======================get Product===========================///
                query="SELECT * FROM `tblproduct` ORDER BY proid DESC";
                dataAdapter  = new MySqlDataAdapter(query,db_con.connection);
                dataTable = new DataTable();
                dataAdapter.Fill(dataTable);
                if(dataTable.Rows.Count>0)
                {
                    foreach (DataRow dr in dataTable.Rows)
                    {
                        ManageProduct md = new ManageProduct();
                        md.proId = int.Parse(dr[0].ToString());
                        md.proName = dr[1].ToString();
                        md.description = dr[2].ToString();
                        md.qty = decimal.Parse(dr[3].ToString());
                        md.uniprice = decimal.Parse(dr[4].ToString());
                        md.imgType = dr[5].ToString();
                        img = (byte[])dr[6];
                        md.image = Convert.ToBase64String(img);
                        md.catId = int.Parse(dr[7].ToString());
                        ls_manage.Add(md);
                    }
                }
                /// ///=======================get Product End===========================///
                /// ///=======================get Product Popp===========================///
                query = "SELECT tblproduct.proid,`proname`,`discription`,`qty`,`uniprice`,`imageType`,`image` FROM tblproduct,tblorder WHERE tblproduct.proid=tblorder.proid GROUP BY tblorder.proid ORDER BY tblorder.proid DESC";
                dataAdapter = new MySqlDataAdapter(query, db_con.connection);
                dataTable = new DataTable();
                dataAdapter.Fill(dataTable);
                if (dataTable.Rows.Count > 0)
                {
                    foreach (DataRow dr in dataTable.Rows)
                    {
                        ManageProduct omd = new ManageProduct();
                        omd.proId = int.Parse(dr[0].ToString());
                        omd.proName = dr[1].ToString();
                        omd.description = dr[2].ToString();
                        omd.qty = decimal.Parse(dr[3].ToString());
                        omd.uniprice = decimal.Parse(dr[4].ToString());
                        omd.imgType = dr[5].ToString();
                        img = (byte[])dr[6];
                        omd.image = Convert.ToBase64String(img);
                        ls_pop.Add(omd);
                    }
                }

                /// ///=======================get Product Popp End===========================///

            }
            catch(Exception ex)
            {
                ViewBag.errCode=ex.HResult;
                ViewBag.errMsg=ex.Message;
            }
            
            pro_obj_list.ls_category = ls_cate;
            pro_obj_list.ls_product=ls_manage;
            pro_obj_list.ls_product_pop=ls_pop;
            return View(pro_obj_list);
        }
        //========================end section home page==============///
        /// 
        /// 
        /// ===================selection show allow category===============///
        /// create funtion to use get data from database================//////
        
        public IActionResult ViewAllProduct()
        {
            /// ///=======================get Product===========================///
            if(!string.IsNullOrEmpty(HttpContext.Session.GetString("username")))
            {
                try
                {
                    query = "SELECT * FROM `tblproduct` ORDER BY proid DESC";
                    dataAdapter = new MySqlDataAdapter(query, db_con.connection);
                    dataTable = new DataTable();
                    dataAdapter.Fill(dataTable);
                    if (dataTable.Rows.Count > 0)
                    {
                        foreach (DataRow dr in dataTable.Rows)
                        {
                            ManageProduct md = new ManageProduct();
                            md.proId = int.Parse(dr[0].ToString());
                            md.proName = dr[1].ToString();
                            md.description = dr[2].ToString();
                            md.qty = decimal.Parse(dr[3].ToString());
                            md.uniprice = decimal.Parse(dr[4].ToString());
                            md.imgType = dr[5].ToString();
                            img = (byte[])dr[6];
                            md.image = Convert.ToBase64String(img);
                            md.catId = int.Parse(dr[7].ToString());
                            ls_manage.Add(md);
                        }
                    }
                }
                catch (Exception ex)
                {
                    ViewBag.errCode = ex.HResult;
                    ViewBag.errMsg = ex.Message;
                }

                return View(ls_manage);
            }
            else return RedirectToAction("Index","Home");
        }
        public IActionResult ClothingMan()
        {
            /// ///=======================get Product===========================///
            if(!string.IsNullOrEmpty(HttpContext.Session.GetString("username")))
            {
                try
                {
                    query = "SELECT * FROM `tblproduct` WHERE `menu`= 1";
                    dataAdapter = new MySqlDataAdapter(query, db_con.connection);
                    dataTable = new DataTable();
                    dataAdapter.Fill(dataTable);
                    if (dataTable.Rows.Count > 0)
                    {
                        foreach (DataRow dr in dataTable.Rows)
                        {
                            ManageProduct md = new ManageProduct();
                            md.proId = int.Parse(dr[0].ToString());
                            md.proName = dr[1].ToString();
                            md.description = dr[2].ToString();
                            md.qty = decimal.Parse(dr[3].ToString());
                            md.uniprice = decimal.Parse(dr[4].ToString());
                            md.imgType = dr[5].ToString();
                            img = (byte[])dr[6];
                            md.image = Convert.ToBase64String(img);
                            md.catId = int.Parse(dr[7].ToString());
                            ls_manage.Add(md);
                        }
                    }
                }
                catch (Exception ex)
                {
                    ViewBag.errCode = ex.HResult;
                    ViewBag.errMsg = ex.Message;
                }
                return View(ls_manage);
            }
            else
            {
                return RedirectToAction("Index","Home");
            }
            
        }
        public IActionResult ClothingWomen()
        {
            try
            {
                query = "SELECT * FROM `tblproduct` WHERE `menu`= 2";
                dataAdapter = new MySqlDataAdapter(query, db_con.connection);
                dataTable = new DataTable();
                dataAdapter.Fill(dataTable);
                if (dataTable.Rows.Count > 0)
                {
                    foreach (DataRow dr in dataTable.Rows)
                    {
                        ManageProduct md = new ManageProduct();
                        md.proId = int.Parse(dr[0].ToString());
                        md.proName = dr[1].ToString();
                        md.description = dr[2].ToString();
                        md.qty = decimal.Parse(dr[3].ToString());
                        md.uniprice = decimal.Parse(dr[4].ToString());
                        md.imgType = dr[5].ToString();

Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor;
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employee</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/dataTable/datatables.css">
    <link rel="stylesheet" href="~/src/css/lightslider.css">
    <link rel="stylesheet" href="~/fontawesome-free-5.15.3-web/fontawesome-free-5.15.3-web/css/all.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/alert.css" />
    
</head>
<body>
   <div class="nav-vertical bg-light  " id="sidebar">
        <div class="mt-0 d-flex align-items-center justify-content-round py-4 px-3 bg-light mb-0">
            <img src="~/image/Jao Liying/L01.jpg"class="rounded-circle img-thumbnail"  width="60px" height="60px" alt="" >
            <div class="ml-4">
                <h4 class="text-mute">@HttpContextAccessor.HttpContext.Session.GetString("username")</h4>
                <div class="text-mute">@HttpContextAccessor.HttpContext.Session.GetString("role")</div>  
            </div>
        </div>
   
        @if(HttpContextAccessor.HttpContext.Session.GetString("role")=="Admin")
        {
                <h2 class="py-4 small text-mute font-weight-bold bg-white px-4">Administator</h2>
        }
        <ul class="nav flex-column">
             @if(HttpContextAccessor.HttpContext.Session.GetString("role")=="Admin")
            {
                <li class="nav-item mb-2">
                    <a asp-controller="Customer" asp-action="dashboad"  class="nav-link text-dark bg-light font-weight-bold">
                        <i class="fa fa-th-large mr-4 text-primary"></i>Dashboad
                    </a>
                </li>
                    
                <li class="nav-item mb-2">
                    <a asp-area="" asp-controller="Employee" asp-action="Employee" class="nav-link text-dark bg-light font-weight-bold"><i class="fa fa-address-card mr-4 text-primary"></i>Employee</a>
                </li>
                <li class="nav-item mb-2">
                    <a asp-area="" asp-controller="ManageProduct" asp-action="ViewManageProduct" class="nav-link text-dark bg-light font-weight-bold"><i class="fa fa-address-card mr-4 text-primary"></i>Manage Product</a>
                </li>
            }
            <h2 class="py-4 small text-mute font-weight-bold bg-white px-4">Customer</h2>
            <li class="nav-item mb-2">
                <a asp-area="" asp-controller="Product" asp-action="HomeProduct" class="nav-link text-dark bg-light font-weight-bold"><i class="fa fa-address-card mr-4 text-primary"></i>Home</a>
            </li>
            <li class="nav-item mb-2 dropdown">
                <a href="#" class="nav-link text-dark bg-light font-weight-bold dropdown-toggle" data-toggle="collapse" data-target="#iscollpae"><i class="fa fa-cubes mr-4 text-primary" ></i>Product </a>
                <div class="navbar-collapse menu-drop collapse" id="iscollpae">
                    <a asp-area="" asp-controller="Product" asp-action="ViewAllProduct" class="dropdown-item item-menu"><i class="fa fa-th-large mr-2 text-primary"></i>All Product</a>
                    <a asp-area="" asp-controller="Product" asp-action="ClothingMan" class="dropdown-item item-menu"><i class="fa fa-th-large mr-2 text-primary"></i>man</a>
                    <a asp-area="" asp-controller="Product" asp-action="ClothingWomen" class="dropdown-item item-menu" ><i class="fa fa-th-large mr-2 text-primary"></i>women</a>
                    <a asp-area="" asp-controller="Product" asp-action="ClothingKids" class="dropdown-item item-menu"><i class="fa fa-th-large mr-2 text-primary"></i>kid</a>
                    <a asp-area="" asp-controller="Product" asp-action="viewShose" class="dropdown-item item-menu"><i class="fa fa-th-large mr-2 text-primary"></i>fashion shoes</a>
                </div>
            </li>
            <li class="nav-item mb-2" >
                <a href="#" class="nav-link text-dark bg-light font-weight-bold"><i class="fab fa-envira mr-4 text-primary"></i>Gallary</a>
            </li>
        </ul>
        <h2 class="py-4 small text-mute font-weight-bold bg-white px-4">Report</h2>
        <ul class="nav flex-column">
            <li class="nav-item mb-2">
                <a asp-area="" asp-controller="ReportOrder" asp-action="ViewReport" class="nav-link text-dark bg-light font-weight-bold"><i
                        class="fas fa-chart-area mr-4 text-primary"></i>Sell Report</a>
            </li>
            <li class="nav-item mb-2">
                <a href="#" class="nav-link text-dark bg-light font-weight-bold"><i
                        class="far fa-chart-bar mr-4 text-primary"></i>Bar Chart</a>
            </li>
            <li class="nav-item mb-2">
                <a asp-controller="Home" asp-action="Logout" class="nav-link text-dark bg-light font-weight-bold"><i
                        class="fas fa-sign-out-alt mr-4 text-primary"></i>Log Out</a>
            </li>
           
        </ul>
    </div>
    <div class="main pt-3 px-5" id="content">
        <div class="toggle" id="toggle">
            <i class="fa fa-bars font-weight-bold"></i>
        </div>
       @RenderBody();
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/dataTable/datatables.js"></script>
    <script src="~/src/js/lightslider.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>