Models/Product/ManageProduct.cs
namespace Employee.Models.Product
{
    public class ManageProduct
    {
        public int proId{get;set;}
        public string proName{get;set;}
        public string description{get;set;}
        public decimal qty{get;set;}
        public decimal uniprice{get;set;}
        public string imgType{get;set;}
        public string image{get;set;}
        public int catId{get;set;}
        public string menu{get;set;}
    }
    public class Categroy
    {
        public int cateId{get;set;}
        public string catename{get;set;}
        public string imgType{get;set;}
        public string image{get;set;}
    }
}

Controllers/Order/OrderController.cs
using System.Data;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using Employee.Models.Product;
using Employee.Models.config;
using Employee.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using Microsoft.AspNetCore.Http;

namespace Employee.Controllers.Order
{
    public class OrderController:Controller
    {
        private Connection db_con = new Connection();
        private MySqlCommand command{get;set;}
        private MySqlDataAdapter dataAdapter{get;set;}
        private DataTable dataTable{get;set;}
        private string query{get;set;}
        private byte[] img{get;set;}
        private int get_proId;
        private ManageProduct pro_mg{get;set;}
        private List<ManageProduct> ls_similar_product = new List<ManageProduct>();
        private List<ManageProduct> ls_more_product = new List<ManageProduct>();
        private Models.ListProduct list_obj=new Models.ListProduct();

        [Route("ViewOrder/{proid?}")]
        public IActionResult ViewOrder(int proid)
        {
            if(!string.IsNullOrEmpty(HttpContext.Session.GetString("username"))) 
            {
                get_proId = proid;
                getToOrderProduct();
                getSimalarAndMoreProduct();                
                return View();
            }
            else return RedirectToAction("Index","Home");
        }
        private string get_proName{get;set;}
        private string get_des{get;set;}
        private decimal getPrice{get;set;}
        public IActionResult getToOrderProduct()
        {
            query = "SELECT * FROM `tblproduct` WHERE proid ="+get_proId;
            dataAdapter = new MySqlDataAdapter(query, db_con.connection);
            dataTable = new DataTable();
            dataAdapter.Fill(dataTable);
            if (dataTable.Rows.Count > 0)
            {
                foreach (DataRow dr in dataTable.Rows)
                {
                    ViewBag.proId = int.Parse(dr[0].ToString());
                    get_proName = dr[1].ToString();
                    ViewBag.proName = get_proName;
                    get_des= dr[2].ToString();
                    ViewBag.description = get_des;
                    ViewBag.uniprice = decimal.Parse(dr[4].ToString());
                    ViewBag.imgType = dr[5].ToString();
                    img = (byte[])dr[6];
                    ViewBag.image = Convert.ToBase64String(img);
                    ViewBag.catId = int.Parse(dr[7].ToString());
                }
            }
            return View();
        }

        public IActionResult getSimalarAndMoreProduct()
        {
            try{
                //Simalar product in order ============================////
                query="SELECT * FROM tblproduct WHERE proname LIKE '%"+get_proName+"%' Limit 8";
                dataAdapter = new MySqlDataAdapter(query, db_con.connection);
                dataTable = new DataTable();
                dataAdapter.Fill(dataTable);

                if (dataTable.Rows.Count > 0)
                {
                    foreach (DataRow dr in dataTable.Rows)
                    {
                        pro_mg = new ManageProduct();
                        pro_mg.proId = int.Parse(dr[0].ToString());
                        pro_mg.proName = dr[1].ToString();
                        pro_mg.description = dr[2].ToString();
                        pro_mg.uniprice = decimal.Parse(dr[4].ToString());
                        pro_mg.imgType = dr[5].ToString();
                        img = (byte[])dr[6];
                        pro_mg.image = Convert.ToBase64String(img);
                        ls_similar_product.Add(pro_mg);
                    }
                }
                //Simalar product in order Exit section============================////
                /// //More product in order start section============================////
                query = "SELECT * FROM `tblproduct` ORDER BY proid DESC";
                dataAdapter = new MySqlDataAdapter(query, db_con.connection);
                dataTable = new DataTable();
                dataAdapter.Fill(dataTable);

                if (dataTable.Rows.Count > 0)
                {
                    foreach (DataRow dr in dataTable.Rows)
                    {
                        pro_mg = new ManageProduct();
                        pro_mg.proId = int.Parse(dr[0].ToString());
                        pro_mg.proName = dr[1].ToString();
                        pro_mg.description = dr[2].ToString();
                        pro_mg.uniprice = decimal.Parse(dr[4].ToString());
                        pro_mg.imgType = dr[5].ToString();
                        img = (byte[])dr[6];
                        pro_mg.image = Convert.ToBase64String(img);
                        ls_more_product.Add(pro_mg);
                    }
                }
            }
            catch(Exception ex)
            {
                ViewBag.errCode=ex.HResult;
                ViewBag.errMsg=ex.Message;
            }
            list_obj.ls_product=ls_similar_product;
            list_obj.ls_product_pop=ls_more_product;

            return View(list_obj);
        }
        //===========order section from customer======================//
        //ClsOrder order = new ClsOrder();
        ErrorMessage message = new ErrorMessage();
        
        DateTime date = DateTime.Now;
        

        public IActionResult PostOrder(ClsOrder order)
        {
            try
            {
                if(message.errCode==0)
                {
                    query="INSERT INTO tblorder(fullanme, Address, phone, proid, deliver, dateOrder, qty_order,price) VALUES (@fullanme,@Address,@phone,@proid,@deliver,@dateOrder,@qty,@price)";
                    command = new MySqlCommand(query,db_con.connection);
                    command.Parameters.AddWithValue("@fullanme", order.fullname);
                    command.Parameters.AddWithValue("@Address", order.address);
                    command.Parameters.AddWithValue("@phone", order.phone);
                    command.Parameters.AddWithValue("@proid",order.proId);
                    command.Parameters.AddWithValue("@deliver","No");
                    command.Parameters.AddWithValue("@dateOrder", date.ToString("dd-MM-yyyy hh:mm"));
                    command.Parameters.AddWithValue("@qty", order.qty);
                    //getPrice=decimal.Parse(string.Format("{0:c}",order.uniprice),NumberStyles.Currency);
                    command.Parameters.AddWithValue("@price",order.uniprice);
                    command.ExecuteNonQuery();
                    message.errCode=1;
                    message.errMsg="Data was saved successfully.";
                }
            }
            catch(Exception ex)
            {
                message.errCode=ex.HResult;
                message.errMsg=ex.Message;
            }
            return Ok(message);
        }
        ////===================More product=================////////////


    }
    
}

Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Employee.Models.Product;
using Employee.Models;
using Employee.Models.config;
using MySql.Data.MySqlClient;
using System.Data;
using Microsoft.AspNetCore.Http;

namespace Employee.Controllers
{
    public class ProductController : Controller
    {  
        private  MySqlCommand command;
        private MySqlDataAdapter dataAdapter;
        private DataTable dataTable;
        private List<Categroy> ls_cate = new List<Categroy>();
        private List<ManageProduct> ls_pop = new List<ManageProduct>();
        private List<ManageProduct> ls_manage = new List<ManageProduct>();
        private ListProduct pro_obj_list = new ListProduct();
        private Connection db_con = new Connection();
        private string query;
        private byte[] img;
        private int cateid;
        public IActionResult HomeProduct(int get_cateid) 
        {
            if(!string.IsNullOrEmpty(HttpContext.Session.GetString("username"))) 
            {
                getDataFromdata();
                //ClothingMan(get_cateid);
                return View();
            }
            else return RedirectToAction("Index","Home");
            
        }

        public IActionResult getDataFromdata()
        {
            try
            {
                //get all category
                query="SELECT * FROM tblcategory";
                dataAdapter = new MySqlDataAdapter(query,db_con.connection);
                dataTable = new DataTable();
                dataAdapter.Fill(dataTable);
                if(dataTable.Rows.Count>0)
                {
                    foreach (DataRow dr in dataTable.Rows)
                    {
                        Categroy categroy = new Categroy();
                        categroy.cateId = int.Parse(dr[0].ToString());
                        categroy.catename = dr[1].ToString();
                        categroy.imgType = dr[2].ToString();
                        img = (byte[])dr[3];
                        categroy.image = Convert.ToBase64String(img);
                        ls_cate.Add(categroy);
                    }
                }
                ///=======================get Category End===========================///
                /// ///=======================get Product===========================///
                query="SELECT * FROM `tblproduct` ORDER BY proid DESC";
                dataAdapter  = new MySqlDataAdapter(query,db_con.connection);
                dataTable = new DataTable();
                dataAdapter.Fill(dataTable);
                if(dataTable.Rows.Count>0)
                {
                    foreach (DataRow dr in dataTable.Rows)
                    {
                        ManageProduct md = new ManageProduct();
                        md.proId = int.Parse(dr[0].ToString());
                        md.proName = dr[1].ToString();
                        md.description = dr[2].ToString();
                        md.qty = decimal.Parse(dr[3].ToString());
                        md.uniprice = decimal.Parse(dr[4].ToString());
                        md.imgType = dr[5].ToString();
                        img = (byte[])dr[6];
                        md.image = Convert.ToBase64String(img);
                        md.catId = int.Parse(dr[7].ToString());
                        ls_manage.Add(md);
                    }
                }
                /// ///=======================get Product End===========================///
                /// ///=======================get Product Popp===========================///
                query = "SELECT tblproduct.proid,`proname`,`discription`,`qty`,`uniprice`,`imageType`,`image` FROM tblproduct,tblorder WHERE tblproduct.proid=tblorder.proid GROUP BY tblorder.proid ORDER BY tblorder.proid DESC";
                dataAdapter = new MySqlDataAdapter(query, db_con.connection);
                dataTable = new DataTable();
                dataAdapter.Fill(dataTable);
                if (dataTable.Rows.Count > 0)
                {
                    foreach (DataRow dr in dataTable.Rows)
                    {
                        ManageProduct omd = new ManageProduct();
                        omd.proId = int.Parse(dr[0].ToString());
                        omd.proName = dr[1].ToString();
                        omd.description = dr[2].ToString();
                        omd.qty = decimal.Parse(dr[3].ToString());
                        omd.uniprice = decimal.Parse(dr[4].ToString());
                        omd.imgType = dr[5].ToString();
                        img = (byte[])dr[6];
                        omd.image = Convert.ToBase64String(img);
                        ls_pop.Add(omd);
                    }
                }

                /// ///=======================get Product Popp End===========================///

            }
            catch(Exception ex)
            {
                ViewBag.errCode=ex.HResult;
                ViewBag.errMsg=ex.Message;
            }
            
            pro_obj_list.ls_category = ls_cate;
            pro_obj_list.ls_product=ls_manage;
            pro_obj_list.ls_product_pop=ls_pop;
            return View(pro_obj_list);
        }
        //========================end section home page==============///
        /// 
        /// 
        /// ===================selection show allow category===============///
        /// create funtion to use get data from database================//////
        
        public IActionResult ViewAllProduct()
        {
            /// ///=======================get Product===========================///
            if(!string.IsNullOrEmpty(HttpContext.Session.GetString("username")))
            {
                try
                {
                    query = "SELECT * FROM `tblproduct` ORDER BY proid DESC";
                    dataAdapter = new MySqlDataAdapter(query, db_con.connection);
                    dataTable = new DataTable();
                    dataAdapter.Fill(dataTable);
                    if (dataTable.Rows.Count > 0)
                    {
                        foreach (DataRow dr in dataTable.Rows)
                        {
                            ManageProduct md = new ManageProduct();
                            md.proId = int.Parse(dr[0].ToString());
                            md.proName = dr[1].ToString();
                            md.description = dr[2].ToString();
                            md.qty = decimal.Parse(dr[3].ToString());
                            md.uniprice = decimal.Parse(dr[4].ToString());
                            md.imgType = dr[5].ToString();
                            img = (byte[])dr[6];
                            md.image = Convert.ToBase64String(img);
                            md.catId = int.Parse(dr[7].ToString());
                            ls_manage.Add(md);
                        }
                    }
                }
                catch (Exception ex)
                {
                    ViewBag.errCode = ex.HResult;
                    ViewBag.errMsg = ex.Message;
                }

                return View(ls_manage);
            }
            else return RedirectToAction("Index","Home");
        }
        public IActionResult ClothingMan()
        {
            /// ///=======================get Product===========================///
            if(!string.IsNullOrEmpty(HttpContext.Session.GetString("username")))
            {
                try
                {
                    query = "SELECT * FROM `tblproduct` WHERE `menu`= 1";
                    dataAdapter = new MySqlDataAdapter(query, db_con.connection);
                    dataTable = new DataTable();
                    dataAdapter.Fill(dataTable);
                    if (dataTable.Rows.Count > 0)
                    {
                        foreach (DataRow dr in dataTable.Rows)
                        {
                            ManageProduct md = new ManageProduct();
                            md.proId = int.Parse(dr[0].ToString());
                            md.proName = dr[1].ToString();
                            md.description = dr[2].ToString();
                            md.qty = decimal.Parse(dr[3].ToString());
                            md.uniprice = decimal.Parse(dr[4].ToString());
                            md.imgType = dr[5].ToString();
                            img = (byte[])dr[6];
                            md.image = Convert.ToBase64String(img);
                            md.catId = int.Parse(dr[7].ToString());
                            ls_manage.Add(md);
                        }
                    }
                }
                catch (Exception ex)
                {
                    ViewBag.errCode = ex.HResult;
                    ViewBag.errMsg = ex.Message;
                }
                return View(ls_manage);
            }
            else
            {
                return RedirectToAction("Index","Home");
            }
            
        }
        public IActionResult ClothingWomen()
        {
            try
            {
                query = "SELECT * FROM `tblproduct` WHERE `menu`= 2";
                dataAdapter = new MySqlDataAdapter(query, db_con.connection);
                dataTable = new DataTable();
                dataAdapter.Fill(dataTable);
                if (dataTable.Rows.Count > 0)
                {
                    foreach (DataRow dr in dataTable.Rows)
                    {
                        ManageProduct md = new ManageProduct();
                        md.proId = int.Parse(dr[0].ToString());
                        md.proName = dr[1].ToString();
                        md.description = dr[2].ToString();
                        md.qty = decimal.Parse(dr[3].ToString());
                        md.uniprice = decimal.Parse(dr[4].ToString());
                        md.imgType = dr[5].ToString();

Views/Product/ClothingKids.cshtml
@model List<Employee.Models.Product.ManageProduct>;
@{
    ViewData["Clothing Kids"]="View clothing Kids";
}
<section class="section-new mt-5 bg-white">
    <h3 class="p-3">All Clothing for Kids</h3>
    <div class="row mt-3 p-3">
        @foreach (var item in Model)
        {
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card p-2">
                    <div class="card-text">
                        <div class="box-img">
                            <img src="@item.imgType,@item.image" class="w-100" height="100%" alt="">
                        </div>
                        <div class="detail">
                            <div class="title">@item.proName</div>
                            <i class="fas fa-star yellow"></i>
                            <i class="fas fa-star yellow"></i>
                            <i class="fas fa-star yellow"></i>
                            <i class="fas fa-star yellow"></i>
                            <i class="far fa-star"></i>
                            <div class="price">$@item.uniprice</div>
                        </div>
                    </div>
                    <div class="custom-btn">
                        <a asp-area="" asp-route-proid="@item.proId" asp-controller="Order" asp-action="ViewOrder" class="btn btn-primary btn-block">Order Now</a>
                    </div>
                </div>
            </div>
        }
    </div>
</section>

Views/Product/ClothingMan.cshtml
@model List<Employee.Models.Product.ManageProduct>
@{
    ViewData["Clothing Man"]="View clothing man";
}

<section class="section-new mt-5 bg-white">
    <h3 class="p-3">All Man</h3>
    <div class="row mt-3 p-3">
        @foreach (var item in Model)
        {
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card p-2">
                    <div class="card-text">
                        <div class="box-img">
                            <img src="@item.imgType,@item.image" class="w-100" height="100%" alt="">
                        </div>
                        <div class="detail">
                            <div class="title">@item.proName</div>
                            <i class="fas fa-star yellow"></i>
                            <i class="fas fa-star yellow"></i>
                            <i class="fas fa-star yellow"></i>
                            <i class="fas fa-star yellow"></i>
                            <i class="far fa-star"></i>
                            <div class="price">$@item.uniprice</div>
                        </div>
                    </div>
                    <div class="custom-btn">
                        <a asp-area="" asp-route-proid="@item.proId" asp-controller="Order" asp-action="ViewOrder" class="btn btn-primary btn-block">Order Now</a>
                    </div>
                </div>
            </div>
        }
    </div>
</section>

Views/Product/ClothingWomen.cshtml
@model List<Employee.Models.Product.ManageProduct>
@{
    ViewData["Clothing Women"]="View clothing Women";
}

<section class="section-new mt-5 bg-white">
    <h3 class="p-3">All Clothing for Women</h3>
    <div class="row mt-3 p-3">
        @foreach (var item in Model)
        {
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card p-2">
                    <div class="card-text">
                        <div class="box-img">
                            <img src="@item.imgType,@item.image" class="w-100" height="100%" alt="">
                        </div>
                        <div class="detail">
                            <div class="title">@item.proName</div>
                            <i class="fas fa-star yellow"></i>
                            <i class="fas fa-star yellow"></i>
                            <i class="fas fa-star yellow"></i>
                            <i class="fas fa-star yellow"></i>
                            <i class="far fa-star"></i>
                            <div class="price">$@item.uniprice</div>
                        </div>
                    </div>
                    <div class="custom-btn">
                        <a asp-area="" asp-route-proid="@item.proId" asp-controller="Order" asp-action="ViewOrder" class="btn btn-primary btn-block">Order Now</a>
                    </div>
                </div>
            </div>
        }
    </div>
</section>

Views/Product/HomeProduct.cshtml
 @model Employee.Models.ListProduct;
 @{
     ViewData["HomeProduct"]="View Home Product";
 }
 <div class="section-clothing mb-4 mt-0 pt-0 ">  
    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active img-beaner">
                <img src="~/img/s.jpg" class="d-block w-100" height="100%" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/img/slide-1.jpg" class="d-block w-100" height="100%" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/img/slide-2.jpg" class="d-block w-100" height="100%" alt="...">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
 </div>

 <!-------------------------section Category----------------------->

 <div class="catgetories mb-4"> 
    <h3 class="p-3">Category</h3>
    <div class="row mt-3">
        @foreach (var item in Model.ls_category)
        {
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card p-2">
                    <div class="card-text">
                        <div class="box-img">
                            <img src="@item.imgType,@item.image" class="w-100" height="100%" alt="">
                        </div>
                        <div class="detail">
                            <div class="title">@item.catename</div>
                                <i class="fas fa-star yellow"></i>
                                <i class="fas fa-star yellow"></i>
                                <i class="fas fa-star yellow"></i>
                                <i class="fas fa-star yellow"></i>
                                <i class="far fa-star"></i>
                            </div>
                        </div>
                        <div class="custom-btn">
                                <a asp-route-id="@item.cateId" asp-area="" asp-controller="Product" asp-action="ViewProductByCategroy" class="btn btn-primary btn-block">View More</a>
                        </div>
                </div>
            </div>
        }
    </div>
 </div>

<!-------------------------section New Product----------------------->

<section class="section-new mb-4 bg-white">
    <h3 class="p-3">New Product</h3>
    <div class="row mt-3">
        @foreach (var item in Model.ls_product)
        {
            <div class="col-xl-3 col-md-6 mb-4">
             <div class="card p-2">
                <div class="card-text">
                    <div class="box-img">
                        <img src="@item.imgType,@item.image" class="w-100" height="100%" alt="">
                    </div>
                    <div class="detail">
                        <div class="title">@item.proName</div>
                        <i class="fas fa-star yellow"></i>
                        <i class="fas fa-star yellow"></i>
                        <i class="fas fa-star yellow"></i>
                        <i class="fas fa-star yellow"></i>
                        <i class="far fa-star"></i>
                        <div class="price">$@item.uniprice</div>
                    </div>
                 </div>
                <div class="custom-btn">
                    <a asp-area="" asp-route-proid="@item.proId" asp-controller="Order" asp-action="ViewOrder" class="btn btn-primary btn-block">View Detail</a>
                </div>
            </div>
            </div>
        }
        
    </div>
</section>

<!-------------------------section popular product----------------------->

<section class="poppular-product bg-white mb-4">
    <h3 class="p-3">Poppular Product</h3>
    <div class="row mt-3">
        @foreach (var item in Model.ls_product_pop)
        {
        <div class="col-xl-3 col-md-6 mb-4">
             <div class="card p-2">
                <div class="card-text">
                    <div class="box-img">
                        <img src="@item.imgType,@item.image" class="w-100" height="100%" alt="">
                    </div>
                    <div class="detail">
                        <div class="title">@item.proName</div>
                        <i class="fas fa-star yellow"></i>
                        <i class="fas fa-star yellow"></i>
                        <i class="fas fa-star yellow"></i>
                        <i class="fas fa-star yellow"></i>
                        <i class="far fa-star"></i>
                        <div class="price">$@item.uniprice</div>
                    </div>
                 </div>
                <div class="custom-btn">
                    <a asp-area="" asp-route-proid="@item.proId" asp-controller="Order" asp-action="ViewOrder" class="btn btn-primary btn-block">View Detail</a>
                </div>
            </div>
        </div>
        }
        
    </div>

</section>

Views/Product/ViewAllProduct.cshtml
@model List<Employee.Models.Product.ManageProduct>;
@{
    ViewData["All Product"]="View All Product";
}

<div class="product-all mt-5 pt-3">

    <table class="table">
        <thead>
            <tr>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                 <td>
                    <div class="pro-item">
                        <div class="pro-img">
                            <img src="@item.imgType,@item.image" alt="">
                        </div>
                        <div class="pro-text">
                             <h3>@item.proName</h3>
                            <i class="fas fa-star yellow"></i>
                            <i class="fas fa-star yellow"></i>
                            <i class="fas fa-star yellow"></i>
                             <i class="fas fa-star yellow"></i>
                            <i class="far fa-star"></i>
                            <p>
                                @item.description
                            </p>
                            </div>
                                <div class="pro-detail">
                                    <h3>$@item.uniprice</h3>
                                    <span>Free Shipping</span>
                                    <a asp-area="" asp-route-proid="@item.proId" asp-controller="Order" asp-action="ViewOrder" class="btn btn-primary my-4 btn-block">Order Now</a>
                                    <a href="#" class="heart-wishlist "><i class="fas fa-heart mr-3"></i> Add to wishlist</a>
                                </div>
                            </div>
                        </td>
                    </tr>
            }
            
        </tbody>
    </table>
</div>


<script src="~/lib/jquery/dist/jquery.js"></script>
<script>
    $(function(){
        //datatable
        $('.table').DataTable();
    })
</script>

Views/Product/ViewProductByCategroy.cshtml
@model List<Employee.Models.Product.ManageProduct>;
@{
    ViewData["All Product"]="View All Product With Category";
}

<div class="product-all mt-5 pt-3">

    <div class="alert alert-success"><h2>@ViewBag.id</h2> </div>

    <table class="table">
        <thead>
            <tr>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                 <td>
                    <div class="pro-item">
                        <div class="pro-img">
                            <img src="@item.imgType,@item.image" alt="">
                        </div>
                        <div class="pro-text">
                             <h3>@item.proName</h3>
                            <i class="fas fa-star yellow"></i>
                            <i class="fas fa-star yellow"></i>
                            <i class="fas fa-star yellow"></i>
                             <i class="fas fa-star yellow"></i>
                            <i class="far fa-star"></i>
                            <p>
                                @item.description
                            </p>
                            </div>
                                <div class="pro-detail">
                                    <h3>$@item.uniprice</h3>
                                    <span>Free Shipping</span>
                                    <a asp-area="" asp-route-proid="@item.proId" asp-controller="Order" asp-action="ViewOrder" class="btn btn-primary my-4 btn-block">Order Now</a>
                                    <a href="#" class="heart-wishlist "><i class="fas fa-heart mr-3"></i> Add to wishlist</a>
                                </div>
                            </div>
                        </td>
                    </tr>
            }
            
        </tbody>
    </table>
</div>


<script src="~/lib/jquery/dist/jquery.js"></script>
<script>
    $(function(){
        //datatable
        $('.table').DataTable();
    })
</script>