Controllers/Report/ReportOrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using Employee.Models;
using Employee.Models.config;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;

namespace Employee.Controllers.Report
{
    public class ReportOrderController:Controller
    {
        public IActionResult ViewReport()
        {
            if(!string.IsNullOrEmpty(HttpContext.Session.GetString("username"))) return View();
            else return RedirectToAction("Index","Home");
        }
        private Connection db_connect = new Connection();
        private ErrorMessage message = new ErrorMessage();
        private string query { get; set; }
        private MySqlCommand command { get; set; }
        private MySqlDataAdapter dataAdapter { get; set; }
        private DataTable dataTable { get; set; }
        private List<ClsOrder> list_order=new List<ClsOrder>();
        private decimal get_price_total{get;set;}
        public IActionResult getOrderReport(DateTime FromDate,DateTime ToDate)
        {
            string fd=FromDate.ToString("dd-MM-yyyy");
            string td=ToDate.ToString("dd-MM-yyyy");
            query = "SELECT `oid`,`proname`,`fullanme`,`qty_order`,(price*qty_order) AS Amount,`dateOrder` FROM tblproduct,tblorder WHERE tblproduct.proid=tblorder.proid AND deliver = 'Yes' AND `dateOrder`>='"+fd+"' AND `dateOrder`<='"+td+"'";
            dataAdapter = new MySqlDataAdapter(query,db_connect.connection);
            dataTable = new DataTable();
            dataAdapter.Fill(dataTable);
            foreach(DataRow dr in dataTable.Rows)
            {
                ClsOrder order = new ClsOrder();
                order.orderId=int.Parse(dr[0].ToString());
                order.proName=dr[1].ToString();
                order.fullname=dr[2].ToString();
                order.qty=decimal.Parse(dr[3].ToString());
                decimal Total=decimal.Parse(dr[4].ToString());
                order.uniprice = Total;
                order.orderDate=dr[5].ToString();
                list_order.Add(order);
                get_price_total = get_price_total + Total;
            }
            ViewBag.Total=get_price_total;
            return Ok(list_order);
        }
    }
}

Views/ReportOrder/ViewReport.cshtml
@{
    ViewData["Title"]="View Report";
}
<!--+++++++++++++++++++++++++SScript javascript library+++++++++++++++++++++++++++++++++++++==-->
<script src="~/lib/jquery/dist/jquery.js"></script>
<!--+++++++++++++++++++++++++SScript javascript library Exit+++++++++++++++++++++++++++++++++++++==-->

<div class="section-report bg-white p-3" id="report-seller">
    <button class="btn btn-success ml-3 btn-sm my-4 mt-5" id="btnPrint">Print</button>
    <div class="title"><h3>Selled Daily Report</h3></div>
    <div class="frm-class pb-3 mt-4">
        
        <div class="form-group">
            <label for="">From Day</label>
            <input id="txtFromDate" type="date" class="form-control mb-3">
        </div>
        <div class="form-group mb-2">
            <label for="">To Day</label>
            <input id="txtToDate" type="date" class="form-control mb-3">
        </div>
        <button class="btn btn-info btn-block mt-4" id="btnShowData">Show Data</button>
        <div id="msg" class="alert alert-warning text-center py-2 mt-3 d-none">All fill not allow.</div>
    </div>

    <div class="table-responsive mt-4" id="report-data-seller">
        <h3 class="py-2 bg-warning bordered-bottom mb-4 pl-3">Shopping Online Col.T.D Complany</h3>
        <h3 class="py-3 mt-4 text-center bordered-bottom">List of Sale Report</h3>
        <table class="table hide-count nowrap table-bordered-top" id="order-id">
            <thead>
                <tr class="nowrap">
                    <th>ID</th>
                    <th>Product</th>
                    <th>Customer Name</th>
                    <th>Qualtity</th>
                    <th>Amount</th>
                    <th>Date Order</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
            
        </table>
        <!--
         <div class="total pt-0 mt-0 p-3" >
            <h3>Total : <span class="text-danger font-wieght-bold"> $@ViewBag.Total</span></h3>
        </div>
        -->
    </div>
</div>

<div class="main-alert">
    <i class="icon" id="icon"></i>
    <div class="alert">
        <span></span>
        <i class="fas fa-times text-success"></i>
    </div>
</div>
<script>
    $(function(){
        //datatable 
        var list_obj=[];
        $('#order-id').DataTable({
            data:list_obj,
            'paging':false,
            'sort':false,
            'searching':false,
            'info':false,
            columns:[
                {data:'orderId', autoWidth:true},
                {data:'proName', autoWidth:true},
                {data:'fullname', autoWidth:true},
                {
                    data:'qty', 
                    autoWidth:true,
                    'render':function(qty){
                        return qty+".00";
                    }
                },
                { 
                    data: 'uniprice', 
                    autoWidth:true,
                    'render':function(uniprice){
                        return "$"+uniprice;
                    }
                },
                { data: 'orderDate', autoWidth:true}
               
            ]
        });
        var table=$('#order-id').DataTable();

        $('#btnShowData').click(function(){
            var frdate = $('#txtFromDate').val();
            var todate = $('#txtToDate').val();
            if(frdate!="" && todate!="")
            {
                $('.main-alert').addClass('show');
                $('#icon').addClass('fas fa-check-circle bg-success');
                $('.alert span').text('Congratualations! Data was show');
                setTimeout(function(){
                    $('.main-alert').removeClass('show');
                    $('#icon').removeClass('fas fa-check-circle bg-success');
                    $('.alert span').text('');
                },5000);
                /////==============///
                $.ajax({
                    url: '@Url.Action("getOrderReport", "ReportOrder")',
                    type: 'GET',
                    dataType: 'JSON',
                    data:{ FromDate : frdate, ToDate:todate},
                    success: function (data) {
                        list_obj = []
                        list_obj = data
                        table.clear();
                        table.rows.add(list_obj)
                        table.draw();
                    }
                })
            }
             else {
                $('.main-alert').addClass('show');
                $('.icon').addClass('fas fa-exclamation-circle bg-warning');
                $('.alert span').text('please enter information of date..!');
                setTimeout(function () {
                $('.main-alert').removeClass('show');
                $('.icon').removeClass('fas fa-exclamation-circle bg-warning');
                    $('.alert span').text('');
                }, 5000);
             }
        })
    })
</script>